In [17]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [7]:
A = np.array([[1,0,0],[0,1,0],[0,0,1]])
v = np.array([3,4,5])

b = np.dot(A,v)
print(b)

[3 4 5]


In [10]:
np.linalg.matrix_rank(A)

B = np.array([[1,1,1],[2,2,2],[4,4,4]])
np.linalg.matrix_rank(B)

1

In [16]:
[U,S,V] = np.linalg.svd(B)
print(U)
print(S)
print(V)

[[-2.18217890e-01  9.75900073e-01 -2.02874033e-16]
 [-4.36435780e-01 -9.75900073e-02 -8.94427191e-01]
 [-8.72871561e-01 -1.95180015e-01  4.47213595e-01]]
[7.93725393e+00 4.05396130e-16 0.00000000e+00]
[[-0.57735027 -0.57735027 -0.57735027]
 [ 0.81649658 -0.40824829 -0.40824829]
 [ 0.         -0.70710678  0.70710678]]


In [18]:
P,L,U = sp.linalg.lu(B)
print(P)
print(L)
print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.25 0.   1.  ]]
[[4. 4. 4.]
 [0. 0. 0.]
 [0. 0. 0.]]
